//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MejorAPPte.Localization {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MejorAPPte.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string Aceptar {
            get {
                return ResourceManager.GetString("Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A menudo.
        /// </summary>
        internal static string Amenudo {
            get {
                return ResourceManager.GetString("Amenudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3 - A menudo.
        /// </summary>
        internal static string AMenudoinf {
            get {
                return ResourceManager.GetString("AMenudoinf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a años.
        /// </summary>
        internal static string Anios {
            get {
                return ResourceManager.GetString("Anios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa un nombre para continuar.
        /// </summary>
        internal static string aviso_nombre {
            get {
                return ResourceManager.GetString("aviso_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AVISO.
        /// </summary>
        internal static string AVISOMAYUS {
            get {
                return ResourceManager.GetString("AVISOMAYUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string AvisoSalir {
            get {
                return ResourceManager.GetString("AvisoSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empezar.
        /// </summary>
        internal static string btnStart {
            get {
                return ResourceManager.GetString("btnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Cada cuánto practicas deporte?.
        /// </summary>
        internal static string CadaCuantopr {
            get {
                return ResourceManager.GetString("CadaCuantopr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Casi siempre.
        /// </summary>
        internal static string CasiSiempre {
            get {
                return ResourceManager.GetString("CasiSiempre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 4 - Casi siempre.
        /// </summary>
        internal static string CasiSiempreinf {
            get {
                return ResourceManager.GetString("CasiSiempreinf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        internal static string Cerrar {
            get {
                return ResourceManager.GetString("Cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Cómo Responder?.
        /// </summary>
        internal static string ComoRes {
            get {
                return ResourceManager.GetString("ComoRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Cómo responder?.
        /// </summary>
        internal static string ComoResponder {
            get {
                return ResourceManager.GetString("ComoResponder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        internal static string Confirmar {
            get {
                return ResourceManager.GetString("Confirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar historial test.
        /// </summary>
        internal static string ConsultarHTest {
            get {
                return ResourceManager.GetString("ConsultarHTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Podrás acceder a éstos consejos siempre que quieras haciendo click en tu perfil.
        /// </summary>
        internal static string cuerpoPopupAviso {
            get {
                return ResourceManager.GetString("cuerpoPopupAviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuerda que dedicar tiempo a tu bienestar mental es invertir en tu felicidad. Cuida tu mente como un recurso inigualable..
        /// </summary>
        internal static string descripcion1Carrusel {
            get {
                return ResourceManager.GetString("descripcion1Carrusel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La salud mental es una prioridad y no un lujo. Fortalece tu bienestar emocional para afrontar cualquier desafío..
        /// </summary>
        internal static string descripcion2Carrusel {
            get {
                return ResourceManager.GetString("descripcion2Carrusel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hablar sobre tus emociones y experiencias puede liberar peso emocional y mejorar tu salud mental y bienestar..
        /// </summary>
        internal static string descripcion3Carrusel {
            get {
                return ResourceManager.GetString("descripcion3Carrusel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edad.
        /// </summary>
        internal static string Edad {
            get {
                return ResourceManager.GetString("Edad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar datos.
        /// </summary>
        internal static string EliminDatos {
            get {
                return ResourceManager.GetString("EliminDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar usuario.
        /// </summary>
        internal static string ElimUsuario {
            get {
                return ResourceManager.GetString("ElimUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2 - En alguna ocasion.
        /// </summary>
        internal static string EnAlguna {
            get {
                return ResourceManager.GetString("EnAlguna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En alguna ocasión.
        /// </summary>
        internal static string EnAlgunaO {
            get {
                return ResourceManager.GetString("EnAlgunaO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        internal static string Enviar {
            get {
                return ResourceManager.GetString("Enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esto es un ejemplo de una pregunta del test.
        /// </summary>
        internal static string Estoesunejemplo {
            get {
                return ResourceManager.GetString("Estoesunejemplo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para acceder a los ajustes de usuario primero tienes que registrarte.
        /// </summary>
        internal static string MainAvisoDescr {
            get {
                return ResourceManager.GetString("MainAvisoDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Ups!.
        /// </summary>
        internal static string MainAvisotit {
            get {
                return ResourceManager.GetString("MainAvisotit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar datos.
        /// </summary>
        internal static string ModificarDatos {
            get {
                return ResourceManager.GetString("ModificarDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No ha realizado todavía ningun test.
        /// </summary>
        internal static string NoharealNinT {
            get {
                return ResourceManager.GetString("NoharealNinT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenid@, antes de empezar necesitamos conocerte.
        /// </summary>
        internal static string nombre_registro {
            get {
                return ResourceManager.GetString("nombre_registro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No te olvidas de algo?.
        /// </summary>
        internal static string NoTeOlv {
            get {
                return ResourceManager.GetString("NoTeOlv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1 - Nunca.
        /// </summary>
        internal static string Nunca {
            get {
                return ResourceManager.GetString("Nunca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Podrás acceder a éstos consejos siempre que quieras haciendo click en tu perfil.
        /// </summary>
        internal static string PodrasAcc {
            get {
                return ResourceManager.GetString("PodrasAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Como te llamas?.
        /// </summary>
        internal static string pregunta_nombre {
            get {
                return ResourceManager.GetString("pregunta_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puedes responder seleccionando un número del 1 al 5.
        /// </summary>
        internal static string PuedesResponderSe {
            get {
                return ResourceManager.GetString("PuedesResponderSe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realizado.
        /// </summary>
        internal static string Realizado {
            get {
                return ResourceManager.GetString("Realizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Recuerda!.
        /// </summary>
        internal static string Recuerda {
            get {
                return ResourceManager.GetString("Recuerda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes ser mayor de 11 años para registrarte.
        /// </summary>
        internal static string RegisterDebest {
            get {
                return ResourceManager.GetString("RegisterDebest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa tu edad para continuar.
        /// </summary>
        internal static string RegisterIngresaEdad {
            get {
                return ResourceManager.GetString("RegisterIngresaEdad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Cual es tu género?.
        /// </summary>
        internal static string RegisterPreguntaedad {
            get {
                return ResourceManager.GetString("RegisterPreguntaedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona un avatar.
        /// </summary>
        internal static string RegisterSAvatar {
            get {
                return ResourceManager.GetString("RegisterSAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, selecciona un avatar.
        /// </summary>
        internal static string RegisterSelectAvatar {
            get {
                return ResourceManager.GetString("RegisterSelectAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, selecciona un género.
        /// </summary>
        internal static string RegisterSGenero {
            get {
                return ResourceManager.GetString("RegisterSGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes ser mayor de 11 años para registrarte.
        /// </summary>
        internal static string RegsterAvisoEdad {
            get {
                return ResourceManager.GetString("RegsterAvisoEdad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Femenino.
        /// </summary>
        internal static string RegsterFemenino {
            get {
                return ResourceManager.GetString("RegsterFemenino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Masculino.
        /// </summary>
        internal static string RegsterMasculino {
            get {
                return ResourceManager.GetString("RegsterMasculino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otro.
        /// </summary>
        internal static string RegsterOtro {
            get {
                return ResourceManager.GetString("RegsterOtro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Que edad tienes actualmente?.
        /// </summary>
        internal static string RegsterPreguntaEdad {
            get {
                return ResourceManager.GetString("RegsterPreguntaEdad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si sales se perderán todos los datos de registro.
        /// </summary>
        internal static string RgstPDescSalir {
            get {
                return ResourceManager.GetString("RgstPDescSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se eliminará el usuario y todos sus datos.
        /// </summary>
        internal static string SeEliminusu {
            get {
                return ResourceManager.GetString("SeEliminusu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se guardará tu avance en el test actual.
        /// </summary>
        internal static string SeGuardaraAvance {
            get {
                return ResourceManager.GetString("SeGuardaraAvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un avatar.
        /// </summary>
        internal static string SeleccionAvatar {
            get {
                return ResourceManager.GetString("SeleccionAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sexo.
        /// </summary>
        internal static string Sexo {
            get {
                return ResourceManager.GetString("Sexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siempre.
        /// </summary>
        internal static string Siempre {
            get {
                return ResourceManager.GetString("Siempre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 5 - Siempre.
        /// </summary>
        internal static string Siempreinf {
            get {
                return ResourceManager.GetString("Siempreinf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin datos.
        /// </summary>
        internal static string SinDatos {
            get {
                return ResourceManager.GetString("SinDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si tus preocupaciones con la alimentación están relacionadas con querer ganar más peso o masa muscular, es posible que esta aplicación no sea la indicada para ti en este momento. Estamos trabajando para abordar estas necesidades en futuras versiones..
        /// </summary>
        internal static string SiTusPre {
            get {
                return ResourceManager.GetString("SiTusPre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Test realizados.
        /// </summary>
        internal static string TestRealizados {
            get {
                return ResourceManager.GetString("TestRealizados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TEST TRANSTORNO DE ALIMENTACIÓN.
        /// </summary>
        internal static string TestTrastAlim {
            get {
                return ResourceManager.GetString("TestTrastAlim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Tienes que responder todas las preguntas para pasar a la siguiente página!.
        /// </summary>
        internal static string TienesQueRes {
            get {
                return ResourceManager.GetString("TienesQueRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro.
        /// </summary>
        internal static string TitRegisterpage {
            get {
                return ResourceManager.GetString("TitRegisterpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a test ansiedad completo.
        /// </summary>
        internal static string tituloAnsiedadCompleto {
            get {
                return ResourceManager.GetString("tituloAnsiedadCompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Recuerda!.
        /// </summary>
        internal static string tituloPopupAviso {
            get {
                return ResourceManager.GetString("tituloPopupAviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TEST ANSIEDAD COMPLETO.
        /// </summary>
        internal static string TituloTACompl {
            get {
                return ResourceManager.GetString("TituloTACompl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TEST DE ALIMENTACIÓN.
        /// </summary>
        internal static string TituloTAliment {
            get {
                return ResourceManager.GetString("TituloTAliment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TEST ANSIEDAD RÁPIDO.
        /// </summary>
        internal static string TituloTARap {
            get {
                return ResourceManager.GetString("TituloTARap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        internal static string Volver {
            get {
                return ResourceManager.GetString("Volver", resourceCulture);
            }
        }
    }
}
